const RETRIEVE_CURRENT_BALANCE = 'RETRIEVE_CURRENT_BALANCE';
const RECEIVE_CURRENT_BALANCE = 'RECEIVE_CURRENT_BALANCE';
const GET_CURRENT_BALANCE = 'GET_CURRENT_BALANCE';
const ERROR_CURRENT_BALANCE = 'ERROR_CURRENT_BALANCE';

export {
    RETRIEVE_CURRENT_BALANCE,
    RECEIVE_CURRENT_BALANCE,
    GET_CURRENT_BALANCE,
    ERROR_CURRENT_BALANCE,
};
