export const ERROR_ID_TOKEN = 'ERROR_ID_TOKEN';
export const REQUEST_ID_TOKEN = 'REQUEST_ID_TOKEN';
export const RECEIVE_ID_TOKEN = 'RECEIVE_ID_TOKEN';

export const REQUEST_AUTHENTICATION_STATUS = 'REQUEST_AUTHENTICATION_STATUS';
export const RECEIVE_AUTHENTICATION_STATUS = 'RECEIVE_AUTHENTICATION_STATUS';
export const ERROR_AUTHENTICATION_STATUS = 'ERROR_AUTHENTICATION_STATUS';
export const GET_AUTHENTICATION_STATUS = 'GET_AUTHENTICATION_STATUS';
